apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge5-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techchallenge5
  template:
    metadata:
      labels:
        app: techchallenge5
    spec:
      containers:
      - name: techchallenge5
        image: allanss/techchallenge5
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: techchallenge-lb
spec:
  type: LoadBalancer
  selector:
    app: techchallenge5
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
